package testing;

import org.junit.Test;

public class TestAll {

	@Test public void Access_Valid_1() { TestFile.runTest("Access_Valid_1"); }
	@Test public void Access_Valid_2() { TestFile.runTest("Access_Valid_2"); }
	@Test public void Asserteq() { TestFile.runTest("Asserteq"); }
	@Test public void Assertne() { TestFile.runTest("Assertne"); }
	@Test public void Assume_Valid_1() { TestFile.runTest("Assume_Valid_1"); }
	@Test public void Assume_Valid_2() { TestFile.runTest("Assume_Valid_2"); }
	@Test public void Basic() { TestFile.runTest("Basic"); }
	@Test public void BasicPlus() { TestFile.runTest("BasicPlus"); }
	@Test public void BoolAssign_Valid_1() { TestFile.runTest("BoolAssign_Valid_1"); }
	@Test public void BoolAssign_Valid_2() { TestFile.runTest("BoolAssign_Valid_2"); }
	@Test public void BoolAssign_Valid_3() { TestFile.runTest("BoolAssign_Valid_3"); }
	@Test public void BoolAssign_Valid_4() { TestFile.runTest("BoolAssign_Valid_4"); }
	@Test public void BoolAssign_Valid_5() { TestFile.runTest("BoolAssign_Valid_5"); }
	@Test public void BoolAssign_Valid_6() { TestFile.runTest("BoolAssign_Valid_6"); }
	@Test public void BoolFun_Valid_1() { TestFile.runTest("BoolFun_Valid_1"); }
	@Test public void BoolIfElse_Valid_1() { TestFile.runTest("BoolIfElse_Valid_1"); }
	@Test public void BoolIfElse_Valid_2() { TestFile.runTest("BoolIfElse_Valid_2"); }
	@Test public void BoolList_Valid_1() { TestFile.runTest("BoolList_Valid_1"); }
	@Test public void BoolList_Valid_2() { TestFile.runTest("BoolList_Valid_2"); }
	@Test public void BoolList_Valid_3() { TestFile.runTest("BoolList_Valid_3"); }
	@Test public void BoolRecord_Valid_1() { TestFile.runTest("BoolRecord_Valid_1"); }
	@Test public void BoolRecord_Valid_2() { TestFile.runTest("BoolRecord_Valid_2"); }
	@Test public void BoolRequires_Valid_1() { TestFile.runTest("BoolRequires_Valid_1"); }
	@Test public void BoolReturn_Valid_1() { TestFile.runTest("BoolReturn_Valid_1"); }
	@Test public void Byte_Valid_1() { TestFile.runTest("Byte_Valid_1"); }
	@Test public void Byte_Valid_2() { TestFile.runTest("Byte_Valid_2"); }
	@Test public void Byte_Valid_3() { TestFile.runTest("Byte_Valid_3"); }
	@Test public void Byte_Valid_4() { TestFile.runTest("Byte_Valid_4"); }
	@Test public void Byte_Valid_5() { TestFile.runTest("Byte_Valid_5"); }
	@Test public void Byte_Valid_6() { TestFile.runTest("Byte_Valid_6"); }
	@Test public void Byte_Valid_7() { TestFile.runTest("Byte_Valid_7"); }
	@Test public void Byte_Valid_8() { TestFile.runTest("Byte_Valid_8"); }
	@Test public void Byte_Valid_9() { TestFile.runTest("Byte_Valid_9"); }
	@Test public void Cast_Valid_1() { TestFile.runTest("Cast_Valid_1"); }
	@Test public void Cast_Valid_2() { TestFile.runTest("Cast_Valid_2"); }
	@Test public void Cast_Valid_3() { TestFile.runTest("Cast_Valid_3"); }
	@Test public void Cast_Valid_4() { TestFile.runTest("Cast_Valid_4"); }
	@Test public void Cast_Valid_5() { TestFile.runTest("Cast_Valid_5"); }
	@Test public void Cast_Valid_6() { TestFile.runTest("Cast_Valid_6"); }
	@Test public void Coercion_Valid_1() { TestFile.runTest("Coercion_Valid_1"); }
	@Test public void Coercion_Valid_2() { TestFile.runTest("Coercion_Valid_2"); }
	@Test public void Coercion_Valid_3() { TestFile.runTest("Coercion_Valid_3"); }
	@Test public void Coercion_Valid_4() { TestFile.runTest("Coercion_Valid_4"); }
	@Test public void Coercion_Valid_6() { TestFile.runTest("Coercion_Valid_6"); }
	@Test public void Coercion_Valid_7() { TestFile.runTest("Coercion_Valid_7"); }
	@Test public void Coercion_Valid_9() { TestFile.runTest("Coercion_Valid_9"); }
	@Test public void Complex_Valid_1() { TestFile.runTest("Complex_Valid_1"); }
	@Test public void Complex_Valid_2() { TestFile.runTest("Complex_Valid_2"); }
	@Test public void Complex_Valid_4() { TestFile.runTest("Complex_Valid_4"); }
	@Test public void Complex_Valid_5() { TestFile.runTest("Complex_Valid_5"); }
	@Test public void Complex_Valid_6() { TestFile.runTest("Complex_Valid_6"); }
	@Test public void Complex_Valid_7() { TestFile.runTest("Complex_Valid_7"); }
	@Test public void Complex_Valid_8() { TestFile.runTest("Complex_Valid_8"); }
	@Test public void Constant_Valid_3() { TestFile.runTest("Constant_Valid_3"); }
	@Test public void ConstrainedDictionary_Valid_1() { TestFile.runTest("ConstrainedDictionary_Valid_1"); }
	@Test public void ConstrainedDictionary_Valid_2() { TestFile.runTest("ConstrainedDictionary_Valid_2"); }
	@Test public void ConstrainedInt_Valid_1() { TestFile.runTest("ConstrainedInt_Valid_1"); }
	@Test public void ConstrainedInt_Valid_10() { TestFile.runTest("ConstrainedInt_Valid_10"); }
	@Test public void ConstrainedInt_Valid_12() { TestFile.runTest("ConstrainedInt_Valid_12"); }
	@Test public void ConstrainedInt_Valid_13() { TestFile.runTest("ConstrainedInt_Valid_13"); }
	@Test public void ConstrainedInt_Valid_14() { TestFile.runTest("ConstrainedInt_Valid_14"); }
	@Test public void ConstrainedInt_Valid_15() { TestFile.runTest("ConstrainedInt_Valid_15"); }
	@Test public void ConstrainedInt_Valid_16() { TestFile.runTest("ConstrainedInt_Valid_16"); }
	@Test public void ConstrainedInt_Valid_17() { TestFile.runTest("ConstrainedInt_Valid_17"); }
	@Test public void ConstrainedInt_Valid_18() { TestFile.runTest("ConstrainedInt_Valid_18"); }
	@Test public void ConstrainedInt_Valid_19() { TestFile.runTest("ConstrainedInt_Valid_19"); }
	@Test public void ConstrainedInt_Valid_2() { TestFile.runTest("ConstrainedInt_Valid_2"); }
	@Test public void ConstrainedInt_Valid_20() { TestFile.runTest("ConstrainedInt_Valid_20"); }
	@Test public void ConstrainedInt_Valid_21() { TestFile.runTest("ConstrainedInt_Valid_21"); }
	@Test public void ConstrainedInt_Valid_22() { TestFile.runTest("ConstrainedInt_Valid_22"); }
	@Test public void ConstrainedInt_Valid_23() { TestFile.runTest("ConstrainedInt_Valid_23"); }
	@Test public void ConstrainedInt_Valid_24() { TestFile.runTest("ConstrainedInt_Valid_24"); }
	@Test public void ConstrainedInt_Valid_3() { TestFile.runTest("ConstrainedInt_Valid_3"); }
	@Test public void ConstrainedInt_Valid_4() { TestFile.runTest("ConstrainedInt_Valid_4"); }
	@Test public void ConstrainedInt_Valid_5() { TestFile.runTest("ConstrainedInt_Valid_5"); }
	@Test public void ConstrainedInt_Valid_6() { TestFile.runTest("ConstrainedInt_Valid_6"); }
	@Test public void ConstrainedInt_Valid_8() { TestFile.runTest("ConstrainedInt_Valid_8"); }
	@Test public void ConstrainedList_Valid_1() { TestFile.runTest("ConstrainedList_Valid_1"); }
	@Test public void ConstrainedList_Valid_11() { TestFile.runTest("ConstrainedList_Valid_11"); }
	@Test public void ConstrainedList_Valid_12() { TestFile.runTest("ConstrainedList_Valid_12"); }
	@Test public void ConstrainedList_Valid_14() { TestFile.runTest("ConstrainedList_Valid_14"); }
	@Test public void ConstrainedList_Valid_15() { TestFile.runTest("ConstrainedList_Valid_15"); }
	@Test public void ConstrainedList_Valid_16() { TestFile.runTest("ConstrainedList_Valid_16"); }
	@Test public void ConstrainedList_Valid_17() { TestFile.runTest("ConstrainedList_Valid_17"); }
	@Test public void ConstrainedList_Valid_18() { TestFile.runTest("ConstrainedList_Valid_18"); }
	@Test public void ConstrainedList_Valid_19() { TestFile.runTest("ConstrainedList_Valid_19"); }
	@Test public void ConstrainedList_Valid_2() { TestFile.runTest("ConstrainedList_Valid_2"); }
	@Test public void ConstrainedList_Valid_20() { TestFile.runTest("ConstrainedList_Valid_20"); }
	@Test public void ConstrainedList_Valid_21() { TestFile.runTest("ConstrainedList_Valid_21"); }
	@Test public void ConstrainedList_Valid_22() { TestFile.runTest("ConstrainedList_Valid_22"); }
	@Test public void ConstrainedList_Valid_23() { TestFile.runTest("ConstrainedList_Valid_23"); }
	@Test public void ConstrainedList_Valid_24() { TestFile.runTest("ConstrainedList_Valid_24"); }
	@Test public void ConstrainedList_Valid_25() { TestFile.runTest("ConstrainedList_Valid_25"); }
	@Test public void ConstrainedList_Valid_26() { TestFile.runTest("ConstrainedList_Valid_26"); }
	@Test public void ConstrainedList_Valid_27() { TestFile.runTest("ConstrainedList_Valid_27"); }
	@Test public void ConstrainedList_Valid_3() { TestFile.runTest("ConstrainedList_Valid_3"); }
	@Test public void ConstrainedList_Valid_4() { TestFile.runTest("ConstrainedList_Valid_4"); }
	@Test public void ConstrainedList_Valid_5() { TestFile.runTest("ConstrainedList_Valid_5"); }
	@Test public void ConstrainedList_Valid_6() { TestFile.runTest("ConstrainedList_Valid_6"); }
	@Test public void ConstrainedList_Valid_7() { TestFile.runTest("ConstrainedList_Valid_7"); }
	@Test public void ConstrainedList_Valid_8() { TestFile.runTest("ConstrainedList_Valid_8"); }
	@Test public void ConstrainedList_Valid_9() { TestFile.runTest("ConstrainedList_Valid_9"); }
	@Test public void ConstrainedRecord_Valid_1() { TestFile.runTest("ConstrainedRecord_Valid_1"); }
	@Test public void ConstrainedRecord_Valid_10() { TestFile.runTest("ConstrainedRecord_Valid_10"); }
	@Test public void ConstrainedRecord_Valid_2() { TestFile.runTest("ConstrainedRecord_Valid_2"); }
	@Test public void ConstrainedRecord_Valid_3() { TestFile.runTest("ConstrainedRecord_Valid_3"); }
	@Test public void ConstrainedRecord_Valid_4() { TestFile.runTest("ConstrainedRecord_Valid_4"); }
	@Test public void ConstrainedRecord_Valid_5() { TestFile.runTest("ConstrainedRecord_Valid_5"); }
	@Test public void ConstrainedRecord_Valid_6() { TestFile.runTest("ConstrainedRecord_Valid_6"); }
	@Test public void ConstrainedRecord_Valid_8() { TestFile.runTest("ConstrainedRecord_Valid_8"); }
	@Test public void ConstrainedRecord_Valid_9() { TestFile.runTest("ConstrainedRecord_Valid_9"); }
	@Test public void ConstrainedReference_Valid_1() { TestFile.runTest("ConstrainedReference_Valid_1"); }
	@Test public void ConstrainedSet_Valid_1() { TestFile.runTest("ConstrainedSet_Valid_1"); }
	@Test public void ConstrainedSet_Valid_2() { TestFile.runTest("ConstrainedSet_Valid_2"); }
	@Test public void ConstrainedSet_Valid_3() { TestFile.runTest("ConstrainedSet_Valid_3"); }
	@Test public void ConstrainedSet_Valid_4() { TestFile.runTest("ConstrainedSet_Valid_4"); }
	@Test public void ConstrainedSet_Valid_5() { TestFile.runTest("ConstrainedSet_Valid_5"); }
	@Test public void ConstrainedSet_Valid_6() { TestFile.runTest("ConstrainedSet_Valid_6"); }
	@Test public void ConstrainedSet_Valid_7() { TestFile.runTest("ConstrainedSet_Valid_7"); }
	@Test public void ConstrainedSet_Valid_8() { TestFile.runTest("ConstrainedSet_Valid_8"); }
	@Test public void ConstrainedSet_Valid_9() { TestFile.runTest("ConstrainedSet_Valid_9"); }
	@Test public void ConstrainedTuple_Valid_1() { TestFile.runTest("ConstrainedTuple_Valid_1"); }
	@Test public void ConstrainedTuple_Valid_2() { TestFile.runTest("ConstrainedTuple_Valid_2"); }
	@Test public void ConstrainedUnion_Valid_1() { TestFile.runTest("ConstrainedUnion_Valid_1"); }
	@Test public void Contractive_Valid_2() { TestFile.runTest("Contractive_Valid_2"); }
	@Test public void DecimalAssignment_Valid_1() { TestFile.runTest("DecimalAssignment_Valid_1"); }
	@Test public void Define_Valid_1() { TestFile.runTest("Define_Valid_1"); }
	@Test public void Define_Valid_2() { TestFile.runTest("Define_Valid_2"); }
	@Test public void Define_Valid_3() { TestFile.runTest("Define_Valid_3"); }
	@Test public void Define_Valid_4() { TestFile.runTest("Define_Valid_4"); }
	@Test public void Dictionary_Valid_1() { TestFile.runTest("Dictionary_Valid_1"); }
	@Test public void Dictionary_Valid_10() { TestFile.runTest("Dictionary_Valid_10"); }
	@Test public void Dictionary_Valid_11() { TestFile.runTest("Dictionary_Valid_11"); }
	@Test public void Dictionary_Valid_12() { TestFile.runTest("Dictionary_Valid_12"); }
	@Test public void Dictionary_Valid_13() { TestFile.runTest("Dictionary_Valid_13"); }
	@Test public void Dictionary_Valid_14() { TestFile.runTest("Dictionary_Valid_14"); }
	@Test public void Dictionary_Valid_15() { TestFile.runTest("Dictionary_Valid_15"); }
	@Test public void Dictionary_Valid_16() { TestFile.runTest("Dictionary_Valid_16"); }
	@Test public void Dictionary_Valid_2() { TestFile.runTest("Dictionary_Valid_2"); }
	@Test public void Dictionary_Valid_3() { TestFile.runTest("Dictionary_Valid_3"); }
	@Test public void Dictionary_Valid_4() { TestFile.runTest("Dictionary_Valid_4"); }
	@Test public void Dictionary_Valid_5() { TestFile.runTest("Dictionary_Valid_5"); }
	@Test public void Dictionary_Valid_6() { TestFile.runTest("Dictionary_Valid_6"); }
	@Test public void Dictionary_Valid_7() { TestFile.runTest("Dictionary_Valid_7"); }
	@Test public void Dictionary_Valid_8() { TestFile.runTest("Dictionary_Valid_8"); }
	@Test public void Dictionary_Valid_9() { TestFile.runTest("Dictionary_Valid_9"); }
	@Test public void DoWhile_Valid_1() { TestFile.runTest("DoWhile_Valid_1"); }
	@Test public void DoWhile_Valid_2() { TestFile.runTest("DoWhile_Valid_2"); }
	@Test public void DoWhile_Valid_3() { TestFile.runTest("DoWhile_Valid_3"); }
	@Test public void DoWhile_Valid_5() { TestFile.runTest("DoWhile_Valid_5"); }
	@Test public void DoWhile_Valid_6() { TestFile.runTest("DoWhile_Valid_6"); }
	@Test public void EffectiveList_Valid_1() { TestFile.runTest("EffectiveList_Valid_1"); }
	@Test public void Ensures_Valid_1() { TestFile.runTest("Ensures_Valid_1"); }
	@Test public void Ensures_Valid_2() { TestFile.runTest("Ensures_Valid_2"); }
	@Test public void Ensures_Valid_3() { TestFile.runTest("Ensures_Valid_3"); }
	@Test public void Ensures_Valid_4() { TestFile.runTest("Ensures_Valid_4"); }
	@Test public void Ensures_Valid_5() { TestFile.runTest("Ensures_Valid_5"); }
	@Test public void Ensures_Valid_6() { TestFile.runTest("Ensures_Valid_6"); }
	@Test public void Ensures_Valid_7() { TestFile.runTest("Ensures_Valid_7"); }
	@Test public void Ensures_Valid_8() { TestFile.runTest("Ensures_Valid_8"); }
	@Test public void For_Valid_1() { TestFile.runTest("For_Valid_1"); }
	@Test public void For_Valid_10() { TestFile.runTest("For_Valid_10"); }
	@Test public void For_Valid_11() { TestFile.runTest("For_Valid_11"); }
	@Test public void For_Valid_12() { TestFile.runTest("For_Valid_12"); }
	@Test public void For_Valid_13() { TestFile.runTest("For_Valid_13"); }
	@Test public void For_Valid_14() { TestFile.runTest("For_Valid_14"); }
	@Test public void For_Valid_15() { TestFile.runTest("For_Valid_15"); }
	@Test public void For_Valid_16() { TestFile.runTest("For_Valid_16"); }
	@Test public void For_Valid_17() { TestFile.runTest("For_Valid_17"); }
	@Test public void For_Valid_18() { TestFile.runTest("For_Valid_18"); }
	@Test public void For_Valid_19() { TestFile.runTest("For_Valid_19"); }
	@Test public void For_Valid_2() { TestFile.runTest("For_Valid_2"); }
	@Test public void For_Valid_20() { TestFile.runTest("For_Valid_20"); }
	@Test public void For_Valid_4() { TestFile.runTest("For_Valid_4"); }
	@Test public void For_Valid_7() { TestFile.runTest("For_Valid_7"); }
	@Test public void For_Valid_8() { TestFile.runTest("For_Valid_8"); }
	@Test public void For_Valid_9() { TestFile.runTest("For_Valid_9"); }
	@Test public void FunctionRef_Valid_1() { TestFile.runTest("FunctionRef_Valid_1"); }
	@Test public void FunctionRef_Valid_3() { TestFile.runTest("FunctionRef_Valid_3"); }
	@Test public void FunctionRef_Valid_4() { TestFile.runTest("FunctionRef_Valid_4"); }
	@Test public void FunctionRef_Valid_5() { TestFile.runTest("FunctionRef_Valid_5"); }
	@Test public void FunctionRef_Valid_6() { TestFile.runTest("FunctionRef_Valid_6"); }
	@Test public void FunctionRef_Valid_7() { TestFile.runTest("FunctionRef_Valid_7"); }
	@Test public void FunctionRef_Valid_8() { TestFile.runTest("FunctionRef_Valid_8"); }
	@Test public void FunctionRef_Valid_9() { TestFile.runTest("FunctionRef_Valid_9"); }
	@Test public void Function_Valid_1() { TestFile.runTest("Function_Valid_1"); }
	@Test public void Function_Valid_10() { TestFile.runTest("Function_Valid_10"); }
	@Test public void Function_Valid_12() { TestFile.runTest("Function_Valid_12"); }
	@Test public void Function_Valid_13() { TestFile.runTest("Function_Valid_13"); }
	@Test public void Function_Valid_14() { TestFile.runTest("Function_Valid_14"); }
	@Test public void Function_Valid_16() { TestFile.runTest("Function_Valid_16"); }
	@Test public void Function_Valid_17() { TestFile.runTest("Function_Valid_17"); }
	@Test public void Function_Valid_18() { TestFile.runTest("Function_Valid_18"); }
	@Test public void Function_Valid_19() { TestFile.runTest("Function_Valid_19"); }
	@Test public void Function_Valid_2() { TestFile.runTest("Function_Valid_2"); }
	@Test public void Function_Valid_20() { TestFile.runTest("Function_Valid_20"); }
	@Test public void Function_Valid_21() { TestFile.runTest("Function_Valid_21"); }
	@Test public void Function_Valid_3() { TestFile.runTest("Function_Valid_3"); }
	@Test public void Function_Valid_4() { TestFile.runTest("Function_Valid_4"); }
	@Test public void Function_Valid_5() { TestFile.runTest("Function_Valid_5"); }
	@Test public void Function_Valid_6() { TestFile.runTest("Function_Valid_6"); }
	@Test public void Function_Valid_7() { TestFile.runTest("Function_Valid_7"); }
	@Test public void Function_Valid_8() { TestFile.runTest("Function_Valid_8"); }
	@Test public void Function_Valid_9() { TestFile.runTest("Function_Valid_9"); }
	@Test public void HexAssign_Valid_1() { TestFile.runTest("HexAssign_Valid_1"); }
	@Test public void IfElse_Valid_1() { TestFile.runTest("IfElse_Valid_1"); }
	@Test public void IfElse_Valid_2() { TestFile.runTest("IfElse_Valid_2"); }
	@Test public void IfElse_Valid_3() { TestFile.runTest("IfElse_Valid_3"); }
	@Test public void IfElse_Valid_4() { TestFile.runTest("IfElse_Valid_4"); }
	@Test public void IfElse_Valid_5() { TestFile.runTest("IfElse_Valid_5"); }
	@Test public void Import_Valid_1() { TestFile.runTest("Import_Valid_1"); }
	@Test public void Import_Valid_2() { TestFile.runTest("Import_Valid_2"); }
	@Test public void Import_Valid_3() { TestFile.runTest("Import_Valid_3"); }
	@Test public void Import_Valid_6() { TestFile.runTest("Import_Valid_6"); }
	@Test public void IntConst_Valid_1() { TestFile.runTest("IntConst_Valid_1"); }
	@Test public void IntDefine_Valid_1() { TestFile.runTest("IntDefine_Valid_1"); }
	@Test public void IntDefine_Valid_2() { TestFile.runTest("IntDefine_Valid_2"); }
	@Test public void IntDiv_Valid_1() { TestFile.runTest("IntDiv_Valid_1"); }
	@Test public void IntDiv_Valid_3() { TestFile.runTest("IntDiv_Valid_3"); }
	@Test public void IntDiv_Valid_4() { TestFile.runTest("IntDiv_Valid_4"); }
	@Test public void IntDiv_Valid_5() { TestFile.runTest("IntDiv_Valid_5"); }
	@Test public void IntEquals_Valid_1() { TestFile.runTest("IntEquals_Valid_1"); }
	@Test public void IntMul_Valid_1() { TestFile.runTest("IntMul_Valid_1"); }
	@Test public void IntMul_Valid_2() { TestFile.runTest("IntMul_Valid_2"); }
	@Test public void IntOp_Valid_1() { TestFile.runTest("IntOp_Valid_1"); }
	@Test public void Lambda_Valid_1() { TestFile.runTest("Lambda_Valid_1"); }
	@Test public void Lambda_Valid_2() { TestFile.runTest("Lambda_Valid_2"); }
	@Test public void Lambda_Valid_3() { TestFile.runTest("Lambda_Valid_3"); }
	@Test public void Lambda_Valid_4() { TestFile.runTest("Lambda_Valid_4"); }
	@Test public void Lambda_Valid_5() { TestFile.runTest("Lambda_Valid_5"); }
	@Test public void Lambda_Valid_6() { TestFile.runTest("Lambda_Valid_6"); }
	@Test public void Lambda_Valid_7() { TestFile.runTest("Lambda_Valid_7"); }
	@Test public void Lambda_Valid_8() { TestFile.runTest("Lambda_Valid_8"); }
	@Test public void Lambda_Valid_9() { TestFile.runTest("Lambda_Valid_9"); }
	@Test public void LengthOf_Valid_1() { TestFile.runTest("LengthOf_Valid_1"); }
	@Test public void LengthOf_Valid_2() { TestFile.runTest("LengthOf_Valid_2"); }
	@Test public void LengthOf_Valid_3() { TestFile.runTest("LengthOf_Valid_3"); }
	@Test public void LengthOf_Valid_4() { TestFile.runTest("LengthOf_Valid_4"); }
	@Test public void LengthOf_Valid_5() { TestFile.runTest("LengthOf_Valid_5"); }
	@Test public void ListAccess_Valid_1() { TestFile.runTest("ListAccess_Valid_1"); }
	@Test public void ListAccess_Valid_3() { TestFile.runTest("ListAccess_Valid_3"); }
	@Test public void ListAccess_Valid_5() { TestFile.runTest("ListAccess_Valid_5"); }
	@Test public void ListAccess_Valid_8() { TestFile.runTest("ListAccess_Valid_8"); }
	@Test public void ListAccess_Valid_9() { TestFile.runTest("ListAccess_Valid_9"); }
	@Test public void ListAppend_Valid_1() { TestFile.runTest("ListAppend_Valid_1"); }
	@Test public void ListAppend_Valid_11() { TestFile.runTest("ListAppend_Valid_11"); }
	@Test public void ListAppend_Valid_13() { TestFile.runTest("ListAppend_Valid_13"); }
	@Test public void ListAppend_Valid_14() { TestFile.runTest("ListAppend_Valid_14"); }
	@Test public void ListAppend_Valid_2() { TestFile.runTest("ListAppend_Valid_2"); }
	@Test public void ListAppend_Valid_3() { TestFile.runTest("ListAppend_Valid_3"); }
	@Test public void ListAppend_Valid_4() { TestFile.runTest("ListAppend_Valid_4"); }
	@Test public void ListAppend_Valid_5() { TestFile.runTest("ListAppend_Valid_5"); }
	@Test public void ListAppend_Valid_6() { TestFile.runTest("ListAppend_Valid_6"); }
	@Test public void ListAppend_Valid_7() { TestFile.runTest("ListAppend_Valid_7"); }
	@Test public void ListAppend_Valid_8() { TestFile.runTest("ListAppend_Valid_8"); }
	@Test public void ListAppend_Valid_9() { TestFile.runTest("ListAppend_Valid_9"); }
	@Test public void ListAssign_Valid_1() { TestFile.runTest("ListAssign_Valid_1"); }
	@Test public void ListAssign_Valid_11() { TestFile.runTest("ListAssign_Valid_11"); }
	@Test public void ListAssign_Valid_2() { TestFile.runTest("ListAssign_Valid_2"); }
	@Test public void ListAssign_Valid_3() { TestFile.runTest("ListAssign_Valid_3"); }
	@Test public void ListAssign_Valid_4() { TestFile.runTest("ListAssign_Valid_4"); }
	@Test public void ListAssign_Valid_5() { TestFile.runTest("ListAssign_Valid_5"); }
	@Test public void ListAssign_Valid_6() { TestFile.runTest("ListAssign_Valid_6"); }
	@Test public void ListAssign_Valid_7() { TestFile.runTest("ListAssign_Valid_7"); }
	@Test public void ListAssign_Valid_8() { TestFile.runTest("ListAssign_Valid_8"); }
	@Test public void ListAssign_Valid_9() { TestFile.runTest("ListAssign_Valid_9"); }
	@Test public void ListConversion_Valid_1() { TestFile.runTest("ListConversion_Valid_1"); }
	@Test public void ListElemOf_Valid_1() { TestFile.runTest("ListElemOf_Valid_1"); }
	@Test public void ListEmpty_Valid_1() { TestFile.runTest("ListEmpty_Valid_1"); }
	@Test public void ListEquals_Valid_1() { TestFile.runTest("ListEquals_Valid_1"); }
	@Test public void ListGenerator_Valid_1() { TestFile.runTest("ListGenerator_Valid_1"); }
	@Test public void ListGenerator_Valid_2() { TestFile.runTest("ListGenerator_Valid_2"); }
	@Test public void ListGenerator_Valid_3() { TestFile.runTest("ListGenerator_Valid_3"); }
	@Test public void ListGenerator_Valid_5() { TestFile.runTest("ListGenerator_Valid_5"); }
	@Test public void ListLength_Valid_1() { TestFile.runTest("ListLength_Valid_1"); }
	@Test public void ListLength_Valid_2() { TestFile.runTest("ListLength_Valid_2"); }
	@Test public void ListLength_Valid_3() { TestFile.runTest("ListLength_Valid_3"); }
	@Test public void ListRange_Valid_1() { TestFile.runTest("ListRange_Valid_1"); }
	@Test public void ListSublist_Valid_1() { TestFile.runTest("ListSublist_Valid_1"); }
	@Test public void ListSublist_Valid_2() { TestFile.runTest("ListSublist_Valid_2"); }
	@Test public void ListSublist_Valid_3() { TestFile.runTest("ListSublist_Valid_3"); }
	@Test public void ListSublist_Valid_4() { TestFile.runTest("ListSublist_Valid_4"); }
	@Test public void ListSublist_Valid_5() { TestFile.runTest("ListSublist_Valid_5"); }
	@Test public void MessageRef_Valid_1() { TestFile.runTest("MessageRef_Valid_1"); }
	@Test public void MessageRef_Valid_2() { TestFile.runTest("MessageRef_Valid_2"); }
	@Test public void MessageSend_Valid_1() { TestFile.runTest("MessageSend_Valid_1"); }
	@Test public void MessageSend_Valid_2() { TestFile.runTest("MessageSend_Valid_2"); }
	@Test public void MessageSend_Valid_3() { TestFile.runTest("MessageSend_Valid_3"); }
	@Test public void MessageSend_Valid_4() { TestFile.runTest("MessageSend_Valid_4"); }
	@Test public void MessageSend_Valid_5() { TestFile.runTest("MessageSend_Valid_5"); }
	@Test public void MethodCall_Valid_1() { TestFile.runTest("MethodCall_Valid_1"); }
	@Test public void MethodCall_Valid_2() { TestFile.runTest("MethodCall_Valid_2"); }
	@Test public void MethodCall_Valid_3() { TestFile.runTest("MethodCall_Valid_3"); }
	@Test public void MethodCall_Valid_4() { TestFile.runTest("MethodCall_Valid_4"); }
	@Test public void MethodRef_Valid_1() { TestFile.runTest("MethodRef_Valid_1"); }
	@Test public void MethodRef_Valid_2() { TestFile.runTest("MethodRef_Valid_2"); }
	@Test public void Method_Valid_1() { TestFile.runTest("Method_Valid_1"); }
	@Test public void MultiLineComment_Valid_1() { TestFile.runTest("MultiLineComment_Valid_1"); }
	@Test public void MultiLineComment_Valid_2() { TestFile.runTest("MultiLineComment_Valid_2"); }
	@Test public void NegationType_Valid_1() { TestFile.runTest("NegationType_Valid_1"); }
	@Test public void NegationType_Valid_2() { TestFile.runTest("NegationType_Valid_2"); }
	@Test public void NegationType_Valid_4() { TestFile.runTest("NegationType_Valid_4"); }
	@Test public void OpenRecord_Valid_1() { TestFile.runTest("OpenRecord_Valid_1"); }
	@Test public void OpenRecord_Valid_10() { TestFile.runTest("OpenRecord_Valid_10"); }
	@Test public void OpenRecord_Valid_2() { TestFile.runTest("OpenRecord_Valid_2"); }
	@Test public void OpenRecord_Valid_4() { TestFile.runTest("OpenRecord_Valid_4"); }
	@Test public void OpenRecord_Valid_5() { TestFile.runTest("OpenRecord_Valid_5"); }
	@Test public void OpenRecord_Valid_6() { TestFile.runTest("OpenRecord_Valid_6"); }
	@Test public void OpenRecord_Valid_7() { TestFile.runTest("OpenRecord_Valid_7"); }
	@Test public void OpenRecord_Valid_8() { TestFile.runTest("OpenRecord_Valid_8"); }
	@Test public void OpenRecord_Valid_9() { TestFile.runTest("OpenRecord_Valid_9"); }
	@Test public void ProcessAccess_Valid_1() { TestFile.runTest("ProcessAccess_Valid_1"); }
	@Test public void ProcessAccess_Valid_2() { TestFile.runTest("ProcessAccess_Valid_2"); }
	@Test public void Process_Valid_1() { TestFile.runTest("Process_Valid_1"); }
	@Test public void Process_Valid_10() { TestFile.runTest("Process_Valid_10"); }
	@Test public void Process_Valid_11() { TestFile.runTest("Process_Valid_11"); }
	@Test public void Process_Valid_12() { TestFile.runTest("Process_Valid_12"); }
	@Test public void Process_Valid_2() { TestFile.runTest("Process_Valid_2"); }
	@Test public void Process_Valid_3() { TestFile.runTest("Process_Valid_3"); }
	@Test public void Process_Valid_4() { TestFile.runTest("Process_Valid_4"); }
	@Test public void Process_Valid_5() { TestFile.runTest("Process_Valid_5"); }
	@Test public void Process_Valid_6() { TestFile.runTest("Process_Valid_6"); }
	@Test public void Process_Valid_7() { TestFile.runTest("Process_Valid_7"); }
	@Test public void Process_Valid_8() { TestFile.runTest("Process_Valid_8"); }
	@Test public void Process_Valid_9() { TestFile.runTest("Process_Valid_9"); }
	@Test public void Quantifiers_Valid_1() { TestFile.runTest("Quantifiers_Valid_1"); }
	@Test public void Range_Valid_1() { TestFile.runTest("Range_Valid_1"); }
	@Test public void RealConst_Valid_1() { TestFile.runTest("RealConst_Valid_1"); }
	@Test public void RealDiv_Valid_1() { TestFile.runTest("RealDiv_Valid_1"); }
	@Test public void RealDiv_Valid_2() { TestFile.runTest("RealDiv_Valid_2"); }
	@Test public void RealDiv_Valid_3() { TestFile.runTest("RealDiv_Valid_3"); }
	@Test public void RealDiv_Valid_4() { TestFile.runTest("RealDiv_Valid_4"); }
	@Test public void RealDiv_Valid_5() { TestFile.runTest("RealDiv_Valid_5"); }
	@Test public void RealDiv_Valid_6() { TestFile.runTest("RealDiv_Valid_6"); }
	@Test public void RealDiv_Valid_7() { TestFile.runTest("RealDiv_Valid_7"); }
	@Test public void RealNeg_Valid_1() { TestFile.runTest("RealNeg_Valid_1"); }
	@Test public void RealNeg_Valid_2() { TestFile.runTest("RealNeg_Valid_2"); }
	@Test public void RealSplit_Valid_1() { TestFile.runTest("RealSplit_Valid_1"); }
	@Test public void RealSub_Valid_1() { TestFile.runTest("RealSub_Valid_1"); }
	@Test public void RealSub_Valid_2() { TestFile.runTest("RealSub_Valid_2"); }
	@Test public void RealSub_Valid_3() { TestFile.runTest("RealSub_Valid_3"); }
	@Test public void Real_Valid_1() { TestFile.runTest("Real_Valid_1"); }
	@Test public void RecordAccess_Valid_1() { TestFile.runTest("RecordAccess_Valid_1"); }
	@Test public void RecordAccess_Valid_2() { TestFile.runTest("RecordAccess_Valid_2"); }
	@Test public void RecordAssign_Valid_1() { TestFile.runTest("RecordAssign_Valid_1"); }
	@Test public void RecordAssign_Valid_10() { TestFile.runTest("RecordAssign_Valid_10"); }
	@Test public void RecordAssign_Valid_2() { TestFile.runTest("RecordAssign_Valid_2"); }
	@Test public void RecordAssign_Valid_3() { TestFile.runTest("RecordAssign_Valid_3"); }
	@Test public void RecordAssign_Valid_4() { TestFile.runTest("RecordAssign_Valid_4"); }
	@Test public void RecordAssign_Valid_5() { TestFile.runTest("RecordAssign_Valid_5"); }
	@Test public void RecordAssign_Valid_6() { TestFile.runTest("RecordAssign_Valid_6"); }
	@Test public void RecordAssign_Valid_7() { TestFile.runTest("RecordAssign_Valid_7"); }
	@Test public void RecordAssign_Valid_8() { TestFile.runTest("RecordAssign_Valid_8"); }
	@Test public void RecordAssign_Valid_9() { TestFile.runTest("RecordAssign_Valid_9"); }
	@Test public void RecordCoercion_Valid_1() { TestFile.runTest("RecordCoercion_Valid_1"); }
	@Test public void RecordConversion_Valid_1() { TestFile.runTest("RecordConversion_Valid_1"); }
	@Test public void RecordDefine_Valid_1() { TestFile.runTest("RecordDefine_Valid_1"); }
	@Test public void RecordDefine_Valid_2() { TestFile.runTest("RecordDefine_Valid_2"); }
	@Test public void RecursiveType_Valid_1() { TestFile.runTest("RecursiveType_Valid_1"); }
	@Test public void RecursiveType_Valid_10() { TestFile.runTest("RecursiveType_Valid_10"); }
	@Test public void RecursiveType_Valid_11() { TestFile.runTest("RecursiveType_Valid_11"); }
	@Test public void RecursiveType_Valid_12() { TestFile.runTest("RecursiveType_Valid_12"); }
	@Test public void RecursiveType_Valid_13() { TestFile.runTest("RecursiveType_Valid_13"); }
	@Test public void RecursiveType_Valid_14() { TestFile.runTest("RecursiveType_Valid_14"); }
	@Test public void RecursiveType_Valid_15() { TestFile.runTest("RecursiveType_Valid_15"); }
	@Test public void RecursiveType_Valid_16() { TestFile.runTest("RecursiveType_Valid_16"); }
	@Test public void RecursiveType_Valid_17() { TestFile.runTest("RecursiveType_Valid_17"); }
	@Test public void RecursiveType_Valid_18() { TestFile.runTest("RecursiveType_Valid_18"); }
	@Test public void RecursiveType_Valid_19() { TestFile.runTest("RecursiveType_Valid_19"); }
	@Test public void RecursiveType_Valid_2() { TestFile.runTest("RecursiveType_Valid_2"); }
	@Test public void RecursiveType_Valid_20() { TestFile.runTest("RecursiveType_Valid_20"); }
	@Test public void RecursiveType_Valid_21() { TestFile.runTest("RecursiveType_Valid_21"); }
	@Test public void RecursiveType_Valid_22() { TestFile.runTest("RecursiveType_Valid_22"); }
	@Test public void RecursiveType_Valid_23() { TestFile.runTest("RecursiveType_Valid_23"); }
	@Test public void RecursiveType_Valid_24() { TestFile.runTest("RecursiveType_Valid_24"); }
	@Test public void RecursiveType_Valid_25() { TestFile.runTest("RecursiveType_Valid_25"); }
	@Test public void RecursiveType_Valid_26() { TestFile.runTest("RecursiveType_Valid_26"); }
	@Test public void RecursiveType_Valid_27() { TestFile.runTest("RecursiveType_Valid_27"); }
	@Test public void RecursiveType_Valid_30() { TestFile.runTest("RecursiveType_Valid_30"); }
	@Test public void RecursiveType_Valid_31() { TestFile.runTest("RecursiveType_Valid_31"); }
	@Test public void RecursiveType_Valid_6() { TestFile.runTest("RecursiveType_Valid_6"); }
	@Test public void RecursiveType_Valid_7() { TestFile.runTest("RecursiveType_Valid_7"); }
	@Test public void RecursiveType_Valid_8() { TestFile.runTest("RecursiveType_Valid_8"); }
	@Test public void RecursiveType_Valid_9() { TestFile.runTest("RecursiveType_Valid_9"); }
	@Test public void Reference_Valid_1() { TestFile.runTest("Reference_Valid_1"); }
	@Test public void Reference_Valid_2() { TestFile.runTest("Reference_Valid_2"); }
	@Test public void Reference_Valid_3() { TestFile.runTest("Reference_Valid_3"); }
	@Test public void Reference_Valid_4() { TestFile.runTest("Reference_Valid_4"); }
	@Test public void Reference_Valid_5() { TestFile.runTest("Reference_Valid_5"); }
	@Test public void Remainder_Valid_1() { TestFile.runTest("Remainder_Valid_1"); }
	@Test public void Requires_Valid_1() { TestFile.runTest("Requires_Valid_1"); }
	@Test public void Resolution_Valid_1() { TestFile.runTest("Resolution_Valid_1"); }
	@Test public void SetAssign_Valid_1() { TestFile.runTest("SetAssign_Valid_1"); }
	@Test public void SetAssign_Valid_2() { TestFile.runTest("SetAssign_Valid_2"); }
	@Test public void SetAssign_Valid_3() { TestFile.runTest("SetAssign_Valid_3"); }
	@Test public void SetDefine_Valid_1() { TestFile.runTest("SetDefine_Valid_1"); }
	@Test public void SetDefine_Valid_2() { TestFile.runTest("SetDefine_Valid_2"); }
	@Test public void SetDefine_Valid_3() { TestFile.runTest("SetDefine_Valid_3"); }
	@Test public void SetDifference_Valid_1() { TestFile.runTest("SetDifference_Valid_1"); }
	@Test public void SetElemOf_Valid_1() { TestFile.runTest("SetElemOf_Valid_1"); }
	@Test public void SetEmpty_Valid_1() { TestFile.runTest("SetEmpty_Valid_1"); }
	@Test public void SetEquals_Valid_1() { TestFile.runTest("SetEquals_Valid_1"); }
	@Test public void SetGenerator_Valid_1() { TestFile.runTest("SetGenerator_Valid_1"); }
	@Test public void SetIntersect_Valid_1() { TestFile.runTest("SetIntersect_Valid_1"); }
	@Test public void SetIntersect_Valid_2() { TestFile.runTest("SetIntersect_Valid_2"); }
	@Test public void SetIntersection_Valid_1() { TestFile.runTest("SetIntersection_Valid_1"); }
	@Test public void SetIntersection_Valid_2() { TestFile.runTest("SetIntersection_Valid_2"); }
	@Test public void SetIntersection_Valid_3() { TestFile.runTest("SetIntersection_Valid_3"); }
	@Test public void SetIntersection_Valid_4() { TestFile.runTest("SetIntersection_Valid_4"); }
	@Test public void SetIntersection_Valid_5() { TestFile.runTest("SetIntersection_Valid_5"); }
	@Test public void SetIntersection_Valid_6() { TestFile.runTest("SetIntersection_Valid_6"); }
	@Test public void SetIntersection_Valid_7() { TestFile.runTest("SetIntersection_Valid_7"); }
	@Test public void SetLength_Valid_1() { TestFile.runTest("SetLength_Valid_1"); }
	@Test public void SetNull_Valid_1() { TestFile.runTest("SetNull_Valid_1"); }
	@Test public void SetSubset_Valid_1() { TestFile.runTest("SetSubset_Valid_1"); }
	@Test public void SetSubset_Valid_10() { TestFile.runTest("SetSubset_Valid_10"); }
	@Test public void SetSubset_Valid_11() { TestFile.runTest("SetSubset_Valid_11"); }
	@Test public void SetSubset_Valid_12() { TestFile.runTest("SetSubset_Valid_12"); }
	@Test public void SetSubset_Valid_2() { TestFile.runTest("SetSubset_Valid_2"); }
	@Test public void SetSubset_Valid_3() { TestFile.runTest("SetSubset_Valid_3"); }
	@Test public void SetSubset_Valid_4() { TestFile.runTest("SetSubset_Valid_4"); }
	@Test public void SetSubset_Valid_5() { TestFile.runTest("SetSubset_Valid_5"); }
	@Test public void SetSubset_Valid_6() { TestFile.runTest("SetSubset_Valid_6"); }
	@Test public void SetSubset_Valid_7() { TestFile.runTest("SetSubset_Valid_7"); }
	@Test public void SetSubset_Valid_8() { TestFile.runTest("SetSubset_Valid_8"); }
	@Test public void SetSubset_Valid_9() { TestFile.runTest("SetSubset_Valid_9"); }
	@Test public void SetUnion_Valid_1() { TestFile.runTest("SetUnion_Valid_1"); }
	@Test public void SetUnion_Valid_10() { TestFile.runTest("SetUnion_Valid_10"); }
	@Test public void SetUnion_Valid_11() { TestFile.runTest("SetUnion_Valid_11"); }
	@Test public void SetUnion_Valid_2() { TestFile.runTest("SetUnion_Valid_2"); }
	@Test public void SetUnion_Valid_3() { TestFile.runTest("SetUnion_Valid_3"); }
	@Test public void SetUnion_Valid_4() { TestFile.runTest("SetUnion_Valid_4"); }
	@Test public void SetUnion_Valid_5() { TestFile.runTest("SetUnion_Valid_5"); }
	@Test public void SetUnion_Valid_6() { TestFile.runTest("SetUnion_Valid_6"); }
	@Test public void SetUnion_Valid_7() { TestFile.runTest("SetUnion_Valid_7"); }
	@Test public void SetUnion_Valid_8() { TestFile.runTest("SetUnion_Valid_8"); }
	@Test public void SetUnion_Valid_9() { TestFile.runTest("SetUnion_Valid_9"); }
	@Test public void SingleLineComment_Valid_1() { TestFile.runTest("SingleLineComment_Valid_1"); }
	@Test public void Skip_Valid_1() { TestFile.runTest("Skip_Valid_1"); }
	@Test public void String_Valid_1() { TestFile.runTest("String_Valid_1"); }
	@Test public void String_Valid_2() { TestFile.runTest("String_Valid_2"); }
	@Test public void String_Valid_3() { TestFile.runTest("String_Valid_3"); }
	@Test public void String_Valid_4() { TestFile.runTest("String_Valid_4"); }
	@Test public void String_Valid_5() { TestFile.runTest("String_Valid_5"); }
	@Test public void String_Valid_6() { TestFile.runTest("String_Valid_6"); }
	@Test public void String_Valid_7() { TestFile.runTest("String_Valid_7"); }
	@Test public void String_Valid_8() { TestFile.runTest("String_Valid_8"); }
	@Test public void Subtype_Valid_1() { TestFile.runTest("Subtype_Valid_1"); }
	@Test public void Subtype_Valid_10() { TestFile.runTest("Subtype_Valid_10"); }
	@Test public void Subtype_Valid_11() { TestFile.runTest("Subtype_Valid_11"); }
	@Test public void Subtype_Valid_12() { TestFile.runTest("Subtype_Valid_12"); }
	@Test public void Subtype_Valid_13() { TestFile.runTest("Subtype_Valid_13"); }
	@Test public void Subtype_Valid_14() { TestFile.runTest("Subtype_Valid_14"); }
	@Test public void Subtype_Valid_2() { TestFile.runTest("Subtype_Valid_2"); }
	@Test public void Subtype_Valid_3() { TestFile.runTest("Subtype_Valid_3"); }
	@Test public void Subtype_Valid_4() { TestFile.runTest("Subtype_Valid_4"); }
	@Test public void Subtype_Valid_5() { TestFile.runTest("Subtype_Valid_5"); }
	@Test public void Subtype_Valid_6() { TestFile.runTest("Subtype_Valid_6"); }
	@Test public void Subtype_Valid_7() { TestFile.runTest("Subtype_Valid_7"); }
	@Test public void Subtype_Valid_8() { TestFile.runTest("Subtype_Valid_8"); }
	@Test public void Subtype_Valid_9() { TestFile.runTest("Subtype_Valid_9"); }
	@Test public void Switch_Valid_1() { TestFile.runTest("Switch_Valid_1"); }
	@Test public void Switch_Valid_10() { TestFile.runTest("Switch_Valid_10"); }
	@Test public void Switch_Valid_11() { TestFile.runTest("Switch_Valid_11"); }
	@Test public void Switch_Valid_12() { TestFile.runTest("Switch_Valid_12"); }
	@Test public void Switch_Valid_13() { TestFile.runTest("Switch_Valid_13"); }
	@Test public void Switch_Valid_2() { TestFile.runTest("Switch_Valid_2"); }
	@Test public void Switch_Valid_3() { TestFile.runTest("Switch_Valid_3"); }
	@Test public void Switch_Valid_4() { TestFile.runTest("Switch_Valid_4"); }
	@Test public void Switch_Valid_5() { TestFile.runTest("Switch_Valid_5"); }
	@Test public void Switch_Valid_6() { TestFile.runTest("Switch_Valid_6"); }
	@Test public void Switch_Valid_7() { TestFile.runTest("Switch_Valid_7"); }
	@Test public void Switch_Valid_8() { TestFile.runTest("Switch_Valid_8"); }
	@Test public void Switch_Valid_9() { TestFile.runTest("Switch_Valid_9"); }
	@Test public void Syntax_Valid_1() { TestFile.runTest("Syntax_Valid_1"); }
	@Test public void TupleType_Valid_1() { TestFile.runTest("TupleType_Valid_1"); }
	@Test public void TupleType_Valid_2() { TestFile.runTest("TupleType_Valid_2"); }
	@Test public void TupleType_Valid_3() { TestFile.runTest("TupleType_Valid_3"); }
	@Test public void TupleType_Valid_4() { TestFile.runTest("TupleType_Valid_4"); }
	@Test public void TupleType_Valid_5() { TestFile.runTest("TupleType_Valid_5"); }
	@Test public void TupleType_Valid_6() { TestFile.runTest("TupleType_Valid_6"); }
	@Test public void TupleType_Valid_7() { TestFile.runTest("TupleType_Valid_7"); }
	@Test public void TupleType_Valid_8() { TestFile.runTest("TupleType_Valid_8"); }
	@Test public void TypeEquals_Valid_1() { TestFile.runTest("TypeEquals_Valid_1"); }
	@Test public void TypeEquals_Valid_10() { TestFile.runTest("TypeEquals_Valid_10"); }
	@Test public void TypeEquals_Valid_11() { TestFile.runTest("TypeEquals_Valid_11"); }
	@Test public void TypeEquals_Valid_12() { TestFile.runTest("TypeEquals_Valid_12"); }
	@Test public void TypeEquals_Valid_13() { TestFile.runTest("TypeEquals_Valid_13"); }
	@Test public void TypeEquals_Valid_14() { TestFile.runTest("TypeEquals_Valid_14"); }
	@Test public void TypeEquals_Valid_15() { TestFile.runTest("TypeEquals_Valid_15"); }
	@Test public void TypeEquals_Valid_16() { TestFile.runTest("TypeEquals_Valid_16"); }
	@Test public void TypeEquals_Valid_17() { TestFile.runTest("TypeEquals_Valid_17"); }
	@Test public void TypeEquals_Valid_18() { TestFile.runTest("TypeEquals_Valid_18"); }
	@Test public void TypeEquals_Valid_19() { TestFile.runTest("TypeEquals_Valid_19"); }
	@Test public void TypeEquals_Valid_2() { TestFile.runTest("TypeEquals_Valid_2"); }
	@Test public void TypeEquals_Valid_20() { TestFile.runTest("TypeEquals_Valid_20"); }
	@Test public void TypeEquals_Valid_21() { TestFile.runTest("TypeEquals_Valid_21"); }
	@Test public void TypeEquals_Valid_22() { TestFile.runTest("TypeEquals_Valid_22"); }
	@Test public void TypeEquals_Valid_24() { TestFile.runTest("TypeEquals_Valid_24"); }
	@Test public void TypeEquals_Valid_25() { TestFile.runTest("TypeEquals_Valid_25"); }
	@Test public void TypeEquals_Valid_26() { TestFile.runTest("TypeEquals_Valid_26"); }
	@Test public void TypeEquals_Valid_27() { TestFile.runTest("TypeEquals_Valid_27"); }
	@Test public void TypeEquals_Valid_28() { TestFile.runTest("TypeEquals_Valid_28"); }
	@Test public void TypeEquals_Valid_29() { TestFile.runTest("TypeEquals_Valid_29"); }
	@Test public void TypeEquals_Valid_30() { TestFile.runTest("TypeEquals_Valid_30"); }
	@Test public void TypeEquals_Valid_31() { TestFile.runTest("TypeEquals_Valid_31"); }
	@Test public void TypeEquals_Valid_32() { TestFile.runTest("TypeEquals_Valid_32"); }
	@Test public void TypeEquals_Valid_33() { TestFile.runTest("TypeEquals_Valid_33"); }
	@Test public void TypeEquals_Valid_34() { TestFile.runTest("TypeEquals_Valid_34"); }
	@Test public void TypeEquals_Valid_35() { TestFile.runTest("TypeEquals_Valid_35"); }
	@Test public void TypeEquals_Valid_39() { TestFile.runTest("TypeEquals_Valid_39"); }
	@Test public void TypeEquals_Valid_40() { TestFile.runTest("TypeEquals_Valid_40"); }
	@Test public void TypeEquals_Valid_42() { TestFile.runTest("TypeEquals_Valid_42"); }
	@Test public void TypeEquals_Valid_43() { TestFile.runTest("TypeEquals_Valid_43"); }
	@Test public void TypeEquals_Valid_44() { TestFile.runTest("TypeEquals_Valid_44"); }
	@Test public void TypeEquals_Valid_45() { TestFile.runTest("TypeEquals_Valid_45"); }
	@Test public void TypeEquals_Valid_46() { TestFile.runTest("TypeEquals_Valid_46"); }
	@Test public void TypeEquals_Valid_47() { TestFile.runTest("TypeEquals_Valid_47"); }
	@Test public void TypeEquals_Valid_5() { TestFile.runTest("TypeEquals_Valid_5"); }
	@Test public void TypeEquals_Valid_6() { TestFile.runTest("TypeEquals_Valid_6"); }
	@Test public void TypeEquals_Valid_7() { TestFile.runTest("TypeEquals_Valid_7"); }
	@Test public void TypeEquals_Valid_8() { TestFile.runTest("TypeEquals_Valid_8"); }
	@Test public void TypeEquals_Valid_9() { TestFile.runTest("TypeEquals_Valid_9"); }
	@Test public void UnionType_Valid_1() { TestFile.runTest("UnionType_Valid_1"); }
	@Test public void UnionType_Valid_10() { TestFile.runTest("UnionType_Valid_10"); }
	@Test public void UnionType_Valid_11() { TestFile.runTest("UnionType_Valid_11"); }
	@Test public void UnionType_Valid_12() { TestFile.runTest("UnionType_Valid_12"); }
	@Test public void UnionType_Valid_13() { TestFile.runTest("UnionType_Valid_13"); }
	@Test public void UnionType_Valid_14() { TestFile.runTest("UnionType_Valid_14"); }
	@Test public void UnionType_Valid_15() { TestFile.runTest("UnionType_Valid_15"); }
	@Test public void UnionType_Valid_16() { TestFile.runTest("UnionType_Valid_16"); }
	@Test public void UnionType_Valid_18() { TestFile.runTest("UnionType_Valid_18"); }
	@Test public void UnionType_Valid_19() { TestFile.runTest("UnionType_Valid_19"); }
	@Test public void UnionType_Valid_2() { TestFile.runTest("UnionType_Valid_2"); }
	@Test public void UnionType_Valid_20() { TestFile.runTest("UnionType_Valid_20"); }
	@Test public void UnionType_Valid_21() { TestFile.runTest("UnionType_Valid_21"); }
	@Test public void UnionType_Valid_22() { TestFile.runTest("UnionType_Valid_22"); }
	@Test public void UnionType_Valid_23() { TestFile.runTest("UnionType_Valid_23"); }
	@Test public void UnionType_Valid_3() { TestFile.runTest("UnionType_Valid_3"); }
	@Test public void UnionType_Valid_4() { TestFile.runTest("UnionType_Valid_4"); }
	@Test public void UnionType_Valid_5() { TestFile.runTest("UnionType_Valid_5"); }
	@Test public void UnionType_Valid_6() { TestFile.runTest("UnionType_Valid_6"); }
	@Test public void UnionType_Valid_7() { TestFile.runTest("UnionType_Valid_7"); }
	@Test public void UnionType_Valid_8() { TestFile.runTest("UnionType_Valid_8"); }
	@Test public void UnionType_Valid_9() { TestFile.runTest("UnionType_Valid_9"); }
	@Test public void VarDecl_Valid_1() { TestFile.runTest("VarDecl_Valid_1"); }
	@Test public void VarDecl_Valid_2() { TestFile.runTest("VarDecl_Valid_2"); }
	@Test public void VarDecl_Valid_3() { TestFile.runTest("VarDecl_Valid_3"); }
	@Test public void VarDecl_Valid_4() { TestFile.runTest("VarDecl_Valid_4"); }
	@Test public void While_Valid_1() { TestFile.runTest("While_Valid_1"); }
	@Test public void While_Valid_10() { TestFile.runTest("While_Valid_10"); }
	@Test public void While_Valid_11() { TestFile.runTest("While_Valid_11"); }
	@Test public void While_Valid_12() { TestFile.runTest("While_Valid_12"); }
	@Test public void While_Valid_14() { TestFile.runTest("While_Valid_14"); }
	@Test public void While_Valid_16() { TestFile.runTest("While_Valid_16"); }
	@Test public void While_Valid_17() { TestFile.runTest("While_Valid_17"); }
	@Test public void While_Valid_18() { TestFile.runTest("While_Valid_18"); }
	@Test public void While_Valid_19() { TestFile.runTest("While_Valid_19"); }
	@Test public void While_Valid_2() { TestFile.runTest("While_Valid_2"); }
	@Test public void While_Valid_20() { TestFile.runTest("While_Valid_20"); }
	@Test public void While_Valid_21() { TestFile.runTest("While_Valid_21"); }
	@Test public void While_Valid_22() { TestFile.runTest("While_Valid_22"); }
	@Test public void While_Valid_23() { TestFile.runTest("While_Valid_23"); }
	@Test public void While_Valid_24() { TestFile.runTest("While_Valid_24"); }
	@Test public void While_Valid_25() { TestFile.runTest("While_Valid_25"); }
	@Test public void While_Valid_26() { TestFile.runTest("While_Valid_26"); }
	@Test public void While_Valid_27() { TestFile.runTest("While_Valid_27"); }
	@Test public void While_Valid_28() { TestFile.runTest("While_Valid_28"); }
	@Test public void While_Valid_29() { TestFile.runTest("While_Valid_29"); }
	@Test public void While_Valid_3() { TestFile.runTest("While_Valid_3"); }
	@Test public void While_Valid_30() { TestFile.runTest("While_Valid_30"); }
	@Test public void While_Valid_31() { TestFile.runTest("While_Valid_31"); }
	@Test public void While_Valid_32() { TestFile.runTest("While_Valid_32"); }
	@Test public void While_Valid_33() { TestFile.runTest("While_Valid_33"); }
	@Test public void While_Valid_34() { TestFile.runTest("While_Valid_34"); }
	@Test public void While_Valid_35() { TestFile.runTest("While_Valid_35"); }
	@Test public void While_Valid_36() { TestFile.runTest("While_Valid_36"); }
	@Test public void While_Valid_37() { TestFile.runTest("While_Valid_37"); }
	@Test public void While_Valid_38() { TestFile.runTest("While_Valid_38"); }
	@Test public void While_Valid_39() { TestFile.runTest("While_Valid_39"); }
	@Test public void While_Valid_40() { TestFile.runTest("While_Valid_40"); }
	@Test public void While_Valid_41() { TestFile.runTest("While_Valid_41"); }
	@Test public void While_Valid_42() { TestFile.runTest("While_Valid_42"); }
	@Test public void While_Valid_43() { TestFile.runTest("While_Valid_43"); }
	@Test public void While_Valid_44() { TestFile.runTest("While_Valid_44"); }
	@Test public void While_Valid_45() { TestFile.runTest("While_Valid_45"); }
	@Test public void While_Valid_46() { TestFile.runTest("While_Valid_46"); }
	@Test public void While_Valid_9() { TestFile.runTest("While_Valid_9"); }


}
